apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: node-accelerator
  name: node-accelerator
spec:
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30686
  selector:
    app.kubernetes.io/name: node-accelerator
  sessionAffinity: None
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: node-accelerator
  name: node-accelerator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: node-accelerator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: node-accelerator
        app.kubernetes.io/part-of: node-accelerator
    spec:
      containers:
      - image: diegowong/node-accelerator:latest
        imagePullPolicy: IfNotPresent        
        name: node-accelerator
        ports:
        - containerPort: 3000