apiVersion: skaffold/v2beta11
kind: Config
build:
  artifacts:
  - image: node-accelerator    
    context: ../
    docker:
      dockerfile: "Dockerfile"
deploy:
  kubectl:
    manifests:
    - service.yml
    - deployment.yml
portForward:
  - resourceType: service
    resourceName: node-accelerator
    port: 80
    localPort: 3000
profiles:
- name: local
  build:
    local:
      push: false